const productos = [
    {
        id: 1,
        productName: "Auriculares",
        price: 5800,
        quanty: 1,
        img: "../media/auriculares.jpg",
    },
    {
        id: 2,
        productName: "CPU",
        price: 450000,
        quanty: 1,
        img: "../media/CPU.webp",
    },
    {
        id: 3,
        productName: "Microfono Parlante",
        price: 25000,
        quanty: 1,
        img: "../media/microfono-parlante.jpg",
    },
    // {
    //     id: 4,
    //     productName: "Mouse",
    //     price: 3000,
    //     quanty: 10,
    //     img: "../client/media/mous.webp",
    // },
    {
        id: 5,
        productName: "Mouse Color",
        price: 4500,
        quanty: 1,
        img: "../media/mouse-color.jpg",
    },
    // {
    //     id: 6,
    //     productName: "Mouse Negro",
    //     price: 4000,
    //     quanty: 10,
    //     img: "../client/media/mouse-negro.jpg",
    // },
    {
        id: 7,
        productName: "Parlante JBL",
        price: 36000,
        quanty: 1,
        img: "../media/parlantejbl.webp",
    },
    {
        id: 8,
        productName: "Pc Gamer",
        price: 800000,
        quanty: 1,
        img: "../media/pc-gamer.jpg",
    },
    {
        id: 9,
        productName: "Silla Gamer",
        price: 68000,
        quanty: 1,
        img: "../media/silla-gamer-negra.webp",
    },
    {
        id: 10,
        productName: "Teclado",
        price: 4200,
        quanty: 1,
        img: "../media/teclado.jpg",
    },
];